# Site settings
title: Understanding Statistics
email: 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cierareports
github_username:  iamciera

# Build settings
markdown: kramdown
